name: Release Workflow

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: install node
        uses: actions/setup-node@v4 
        with:
          node-version: 20

      - name: Install modules
        run: npm install semantic-release @semantic-release/git @semantic-release/github -D
      
      - name: Run release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
